/*******************************************************************************
* Projeto iNFC-e                                                               *
* Emissao de NFC-e em Java                                                     *
*                                                                              *
* Direitos Autorais Reservados (c) 2014 Ivan S. Vargas                         *
*                                                                              *
*  Você pode obter a última versão desse arquivo na pagina do Projeto iNFC-e   *
* localizado em https://code.google.com/p/infc-e/                              *
*                                                                              *
*  Esta biblioteca é software livre; você pode redistribuí-la e/ou modificá-la *
* sob os termos da Licença Pública Geral Menor do GNU conforme publicada pela  *
* Free Software Foundation; tanto a versão 2.1 da Licença, ou (a seu critério) *
* qualquer versão posterior.                                                   *
*                                                                              *
*  Esta biblioteca é distribuída na expectativa de que seja útil, porém, SEM   *
* NENHUMA GARANTIA; nem mesmo a garantia implícita de COMERCIABILIDADE OU      *
* ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. Consulte a Licença Pública Geral Menor*
* do GNU para mais detalhes. (Arquivo LICENÇA.TXT ou LICENSE.TXT)              *
*                                                                              *
*  Você deve ter recebido uma cópia da Licença Pública Geral Menor do GNU junto*
* com esta biblioteca; se não, escreva para a Free Software Foundation, Inc.,  *
* no endereço 59 Temple Street, Suite 330, Boston, MA 02111-1307 USA.          *
* Você também pode obter uma copia da licença em:                              *
* http://www.opensource.org/licenses/lgpl-license.php                          *
*                                                                              *
*        Ivan S. Vargas  -  ivan@is5.com.br  -  http://www.is5.com.br          *
*                                                                              *
********************************************************************************/
package Frames;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import nfce.Configuracoes;
import nfe.util.Log;
import nfe.util.Util;
import webservices.*;

/**
 *
 * @author Ivan Vargas
 */
public class frmPainel extends javax.swing.JFrame {

    /**
     * Creates new form frmPainel
     */
    public frmPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultarStatusServico = new javax.swing.JButton();
        btnCriarEnviar = new javax.swing.JButton();
        btnConsultarPelaChave = new javax.swing.JToggleButton();
        btnCancelarPorChave = new javax.swing.JButton();
        btnConsultaCadastro = new javax.swing.JButton();
        btnCartaCorrecao = new javax.swing.JButton();
        btnInutilizarNumeracao = new javax.swing.JButton();
        edtOrigem = new javax.swing.JTextField();
        edtDestino = new javax.swing.JTextField();
        edtSHA = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnConsultarStatusServico.setText("Consultar Status do Serviço");
        btnConsultarStatusServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarStatusServicoActionPerformed(evt);
            }
        });

        btnCriarEnviar.setText("Criar e Enviar");
        btnCriarEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEnviarActionPerformed(evt);
            }
        });

        btnConsultarPelaChave.setText("Consultar pela Chave");
        btnConsultarPelaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPelaChaveActionPerformed(evt);
            }
        });

        btnCancelarPorChave.setText("Cancelar NFe por Chave");
        btnCancelarPorChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPorChaveActionPerformed(evt);
            }
        });

        btnConsultaCadastro.setText("Consulta Cadastro");
        btnConsultaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCadastroActionPerformed(evt);
            }
        });

        btnCartaCorrecao.setText("Carta de Correção");
        btnCartaCorrecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartaCorrecaoActionPerformed(evt);
            }
        });

        btnInutilizarNumeracao.setText("Inutilizar Numeração");
        btnInutilizarNumeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInutilizarNumeracaoActionPerformed(evt);
            }
        });

        edtSHA.setText("Hash SHA1");
        edtSHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSHAActionPerformed(evt);
            }
        });

        jButton1.setText("Tentativa 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("HEXA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tentativa 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Get Params");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("QrCode");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Gravar Configurações ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Ler Configurações");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane1.setViewportView(taLog);

        jButton8.setText("Ativar Leitura Log");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarStatusServico, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(btnCriarEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConsultarPelaChave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelarPorChave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConsultaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCartaCorrecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInutilizarNumeracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(edtDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                    .addComponent(edtOrigem, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtSHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarStatusServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriarEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarPelaChave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarPorChave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultaCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCartaCorrecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInutilizarNumeracao))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtSHA)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(edtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-601)/2, (screenSize.height-433)/2, 601, 433);
    }// </editor-fold>//GEN-END:initComponents

    private void defineSaida() {
        taLog.setText(null);
        Log.getInstance().setSaida(taLog);
    }
    
    private void btnConsultarStatusServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarStatusServicoActionPerformed
        // TODO add your handling code here:
        defineSaida();
        
        NfeStatusServico2 s = new NfeStatusServico2();
        s.Executar();

        JOptionPane.showMessageDialog(null, "RETORNO"
                + "\ntpAmb: " + s.Retorno.tpAmb
                + "\nverAplic: " + s.Retorno.verAplic
                + "\ncStat: " + s.Retorno.cStat
                + "\nxMotivo: " + s.Retorno.xMotivo
                + "\ncUF: " + s.Retorno.cUF
                + "\ndhRecbto: " + s.Retorno.dhRecbto
                + "\ntMed: " + s.Retorno.tMed);
    }//GEN-LAST:event_btnConsultarStatusServicoActionPerformed

    private void btnCriarEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEnviarActionPerformed
        // TODO add your handling code here:
        defineSaida();
        nfce.NFCe.Enviar();
    }//GEN-LAST:event_btnCriarEnviarActionPerformed

    private void btnConsultarPelaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPelaChaveActionPerformed
        // TODO add your handling code here:
        defineSaida();
        
        String chave = JOptionPane.showInputDialog(null, "Digite a Chave");

        if (!chave.equals("")) {
            webservices.NfeConsulta2 c = new webservices.NfeConsulta2();
            c.setChave(chave);
            c.Executar();

            if (c.Retorno.cStat != null) {
                JOptionPane.showMessageDialog(null, "RETORNO"
                        + "\ncStat: " + c.Retorno.cStat
                        + "\ncUF: " + c.Retorno.cUF
                        + "\nchNFe: " + c.Retorno.chNFe
                        + "\ntpAmb: " + c.Retorno.tpAmb
                        + "\nverAplic: " + c.Retorno.verAplic
                        + "\nxMotivo: " + c.Retorno.xMotivo
                        + "\ninfoProt.xMotivo: " + c.Retorno.infProt.xMotivo
                        + "\ninfoProt.cStat: " + c.Retorno.infProt.cStat);
            } else {
                JOptionPane.showMessageDialog(null, "Impossível ler informacoes de retorno!");
            }

        }
    }//GEN-LAST:event_btnConsultarPelaChaveActionPerformed

    private void btnCancelarPorChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPorChaveActionPerformed
        // TODO add your handling code here:
        defineSaida();

        String chave = JOptionPane.showInputDialog("Chave", "43131201611275000124550010000009901000009908");
        String idLote = JOptionPane.showInputDialog("Lote", "1");
        String cnpj = JOptionPane.showInputDialog("CNPJ/CPF", "01611275000124");
        String just = JOptionPane.showInputDialog("Justificativa", "isso eh uma justificativa com mais de quinze caracteres");

        if (chave.equals("") || idLote.equals("") || cnpj.equals("") || just.equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos sao obrigatorios.");
        } else {
            webservices.NfeCancelamento2 c = new NfeCancelamento2();

            c.setCNPJ_CPF(cnpj);
            c.setChave(chave);
            c.setJustificativa(just);
            c.setidLote(idLote);

            c.Executar();

            JOptionPane.showMessageDialog(null, "RETORNO\ncStat: " + c.Retorno.cStat
                    + "\nxMotivo: " + c.Retorno.xMotivo
                    + "\ninfProt.cStat: " + c.Retorno.infEvento.cStat
                    + "\ninfProt.xMotivo: " + c.Retorno.infEvento.xMotivo
                    + "\ninfProt.dhRegEvento: " + c.Retorno.infEvento.dhRegEvento);
        }
    }//GEN-LAST:event_btnCancelarPorChaveActionPerformed

    private void btnConsultaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCadastroActionPerformed
        // TODO add your handling code here:
        defineSaida();
        
        String cnpj = JOptionPane.showInputDialog("CNPJ", "01611275000124");
        String uf = JOptionPane.showInputDialog("Estado", "RS");

        if ((cnpj.equals("")) || (uf.equals(""))) {
            JOptionPane.showMessageDialog(null, "Todos os campos sao obrigatórios.");
        } else {
            CadConsultaCadastro2 c = new CadConsultaCadastro2();
            c.setCnpj(cnpj);
            c.setUf(uf);
            c.Executar();

            JOptionPane.showMessageDialog(null, "RETORNO"
                    + "\ncStat: " + c.Retorno.cStat
                    + "\nxMotivo: " + c.Retorno.xMotivo
                    + "\ninfCad.xNome: " + c.Retorno.infCad.xNome
                    + "\ninfCad.xRegApur: " + c.Retorno.infCad.xRegApur
                    + "\ninfCad.ender.xLogr: " + c.Retorno.infCad.ender.xLgr
                    + "\ninfCad.ender.CEP: " + c.Retorno.infCad.ender.CEP);
        }

    }//GEN-LAST:event_btnConsultaCadastroActionPerformed

    private void btnCartaCorrecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaCorrecaoActionPerformed
        // TODO add your handling code here:
        defineSaida();

        String chave = JOptionPane.showInputDialog("Chave", "43131101611275000124550010000008881000008882");
        String idlote = JOptionPane.showInputDialog("ID Lote", "2");
        String nseq = JOptionPane.showInputDialog("Sequencial", "3");
        String correcao = JOptionPane.showInputDialog("Chave", "Correcao a ser considerada, texto livre");

        CartaCorrecao cc = new CartaCorrecao();
        cc.setChNFe(chave);
        cc.setIdLote(idlote);
        cc.setNSeqEvento(nseq);
        cc.setXCorrecao(correcao);
        cc.Executar();

        JOptionPane.showMessageDialog(null, "RETORNO\ncStat: " + cc.Retorno.cStat
                + "\nxMotivo: " + cc.Retorno.xMotivo
                + "\ninfProt.cStat: " + cc.Retorno.infEvento.cStat
                + "\ninfProt.xMotivo: " + cc.Retorno.infEvento.xMotivo
                + "\ninfProt.dhRegEvento: " + cc.Retorno.infEvento.dhRegEvento);
    }//GEN-LAST:event_btnCartaCorrecaoActionPerformed

    private void btnInutilizarNumeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInutilizarNumeracaoActionPerformed
        // TODO add your handling code here:
        defineSaida();
        
        String ano = JOptionPane.showInputDialog("Ano", "14");
        String cnpj = JOptionPane.showInputDialog("CNPJ", "01611275000124");
        String mod = JOptionPane.showInputDialog("Modelo", "66");
        String serie = JOptionPane.showInputDialog("Serie", "1");
        //String amb = JOptionPane.showInputDialog("Tipo Ambiente", "2");
        //String cuf = JOptionPane.showInputDialog("cUF", "43");
        String ini = JOptionPane.showInputDialog("Numeracao Inicial", "100");
        String fim = JOptionPane.showInputDialog("Numeracao Final", "110");
        String just = JOptionPane.showInputDialog("Justificativa", "Digite aqui pq vc esta inutilizando esta numeracao");

        NfeInutilizacao2 i = new NfeInutilizacao2();

        
        i.setAno(ano);
        i.setCNPJ(cnpj);
        i.setMod(mod);
        i.setSerie(serie);
        //i.setTpAmb(amd);
        //i.setcUF(cuf);
        i.setnNFIni(ini);
        i.setnNFFin(fim);
        i.setxJust(just);

        i.Executar();

        JOptionPane.showMessageDialog(null, "RETORNO\ncStat: " + i.Retorno.cStat
                + "\nxMotivo: " + i.Retorno.xMotivo
                + "\nverAplic: " + i.Retorno.verAplic
                + "\ntpAmb: " + i.Retorno.tpAmb
                + "\ndhRecbto: " + i.Retorno.dhRecbto);
    }//GEN-LAST:event_btnInutilizarNumeracaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try
        {
            InputStream in = getClass().getResourceAsStream("/configuracao.dat");
        
            ObjectInputStream objIn = new ObjectInputStream(in);
            
            Configuracoes c = (Configuracoes)objIn.readObject();
            
            JOptionPane.showMessageDialog(null, c.getRAZAO_SOCIAL());
            
                    
        }catch(Exception ex) {
            System.out.println("Erro: " + ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "PATH:\n" + Util.getCurrentDir() );
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        LerLog l = new LerLog();
        l.start();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void edtSHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSHAActionPerformed
        // TODO add your handling code here:
        //String s = GerarQrCode.getSHA1(edtOrigem.getText());


        //stringHexa(gerarHash(frase, "SHA-1"))
  }//GEN-LAST:event_edtSHAActionPerformed

    class LerLog extends Thread {
        public void run() {
            while(1==1) 
            {
                taLog.setText(null);
                taLog.setText( Log.getInstance().getMensagens() );
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmPainel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPainel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPorChave;
    private javax.swing.JButton btnCartaCorrecao;
    private javax.swing.JButton btnConsultaCadastro;
    private javax.swing.JToggleButton btnConsultarPelaChave;
    private javax.swing.JButton btnConsultarStatusServico;
    private javax.swing.JButton btnCriarEnviar;
    private javax.swing.JButton btnInutilizarNumeracao;
    private javax.swing.JTextField edtDestino;
    private javax.swing.JTextField edtOrigem;
    private javax.swing.JButton edtSHA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taLog;
    // End of variables declaration//GEN-END:variables
}
